version: '2.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']
  create_reqs:
    container_name: create_reqs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil req --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']
  edit_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    command: >
      bash -c '
        yum install -y -q -e 0 openssl vim;
        bash
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']
  copy_certs:
    container_name: copy_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    command: cp -r /certs/ /local_certs/
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', './local_certs/:/local_certs/']


volumes: {"certs"}
