# Inspired by:
# `curl -L -O https://raw.githubusercontent.com/elastic/beats/7.4/deploy/docker/filebeat.docker.yml`

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

# enable for local docker discovery
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# output.elasticsearch.index: "customname-%{[agent.version]}-%{+yyyy.MM.dd}"
# setup.template.name: "customname"
# setup.template.pattern: "customname-*"

processors:
  - add_cloud_metadata: ~

# monitoring:
#   enabled: true
#   elasticsearch:
#     # api_key: id:api_key
#     hosts: ["https://esa:9200"]
#     username: 'elastic'
#     password: 'PleaseChangeMe'

# output.elasticsearch:
#   hosts: ["https://es01:9200"]
#   username: 'elastic'
#   password: 'PleaseChangeMe'
#   ssl.certificate_authorities: [ '/certs/ca/ca.crt' ]

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities: ["/certs/ca/ca.crt"]
  ssl.certifcate: "/certs/logstash_client/logstash_client.crt"
  ssl.key: "/certs/logstash_client/logstash_client.key"

# setup.kibana:
#   host: "https://esa:5601"
#   ssl.enabled: true
#   username: "elastic"
#   password: "PleaseChangeMe"
#   ssl.certificate_authorities: ["/certs/ca/ca.crt"]


